### PR TITLE
split api handlers out into separate files

### PR DESCRIPTION
**Pull request by samdfonseca**
Moved a few things around so we're not dealing with one huge file with all the api handlers

### CODE REVIEW

**Comment by dinever** [comment]
@samdfonseca 

This looks good. However, we may need to split other handlers in `admin.go` and `home.go` if we go through this way. What do we think about restructuring the whole `handler` package into 3 packages `handler/admin`, `handler/home`(we can come up with a better name for this) and `handler/api`?

Would love to hear your thoughts.

**Comment by samdfonseca** [comment]
i think thats a great idea. that should help clear up some of the confusion over whats being used for the api handlers vs the template rendering handlers

**Comment by samdfonseca** [comment]
working on fixing the broken tests now

**Comment by samdfonseca** [comment]
@dinever im gonna merge this in unless theres any objections

**Comment by dinever** [comment]
@samdfonseca 

Sure, free feel to merge this if it is finished, and thanks for the contribution! 👍

**Pull request merged**
